import {
  Album,
  Bank,
  BankCheck,
  Benefit,
  Bill,
  Car,
  Chess,
  Child,
  Dots,
  Email,
  Euro,
  Exchange,
  FileTypeNote,
  Fitness,
  Globe,
  Gouv,
  Heart,
  Home,
  Image,
  Justice,
  Laudry,
  Lightning,
  Link,
  People,
  Plane,
  Remboursement,
  Restaurant,
  Restore,
  School,
  Shop,
  Team,
  Telecom,
  Telephone,
  Trash,
  Water,
  Work
} from '@linagora/twake-icons'

const icons = {
  album: Album,
  bank: Bank,
  'bank-check': BankCheck,
  benefit: Benefit,
  bill: Bill,
  car: Car,
  chess: Chess,
  child: Child,
  dots: Dots,
  email: Email,
  euro: Euro,
  exchange: Exchange,
  'file-type-note': FileTypeNote,
  fitness: Fitness,
  globe: Globe,
  gouv: Gouv,
  heart: Heart,
  home: Home,
  image: Image,
  justice: Justice,
  laudry: Laudry,
  lightning: Lightning,
  link: Link,
  people: People,
  plane: Plane,
  remboursement: Remboursement,
  restaurant: Restaurant,
  restore: Restore,
  school: School,
  shop: Shop,
  team: Team,
  telecom: Telecom,
  telephone: Telephone,
  trash: Trash,
  water: Water,
  work: Work
}

export const getTwakeIcon = iconName => icons[iconName] || null
