approvedGitRepositories: # to allow the use of private git repositories
  - "https://github.com/cozy/*"
  - "https://github.com/linagora/*"
  - "https://github.com/konnectors/*"
nodeLinker: node-modules # to avoid using .pnp.cjs files and keep npm compatibility
compressionLevel: mixed # to speed up installation by using a lower compression level for the cache
enableScripts: true # to allow postinstall scripts to run during installation, which is necessary for some packages
npmMinimalAgeGate: 0 # to allow the use of the latest npm version without any age restrictions
