version: "3.4"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tdrive
      POSTGRES_PASSWORD: tdrive_secret
      POSTGRES_USER: tdrive_user
    ports:
      - "5432:5432"

  av:
    image: clamav/clamav:latest
    container_name: av
    ports:
      - 3310:3310
