/**
 * Time to live (bigduration format) for the temporary download link
 * generated by the File Picker.
 *
 * This value is consumed by `makeSharingLink` via its `ttl` option.
 * The short window is enough for the Mail client to fetch the file
 * once it has been attached to a draft.
 *
 * Format reference: https://github.com/justincampbell/bigduration/blob/master/README.md (e.g. "5m", "1h").
 */
export const TEMPORARY_LINK_TTL = '5m'

export const filePickerLinkModes = {
  PUBLIC_LINK: 'public-link',
  TEMPORARY_DOWNLOAD_LINK: 'temporary-download-link',
  REFERENCE: 'reference'
}

/**
 * Error codes used by the File Picker internally to track
 * and display error messages in the UI.
 */
export const filePickerErrorCodes = {
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  SHARING_LINK_FAILED: 'SHARING_LINK_FAILED',
  DOWNLOAD_LINK_FAILED: 'DOWNLOAD_LINK_FAILED'
}

/**
 * Default FilePickerConfig used when the intent client does not send
 * any action config (e.g. legacy callers or the in-app demo button
 * before explicit config is wired). Only the keys whose default
 * matters at runtime are set; the rest (label, allowedMimeTypes,
 * maxFileSize) are filled in by the client or the service locale
 * fallback.
 *
 * allowFolder semantics: sharingLink allows folders (folders can be
 * shared via a public link), downloadLink does not (downloading a
 * folder is not meaningful for an attachment use case).
 */
// TODO with multi selection: enforce maxFileCount and availableSize on
// the downloadLink action when multi-select lands.
export const defaultFilePickerConfig = {
  sharingLink: { allowFolder: true },
  downloadLink: { allowFolder: false },
  reference: null
}
