import { render, waitFor } from '@testing-library/react'
import React from 'react'

import { makeSharingLink } from 'cozy-client/dist/models/sharing'

import {
  filePickerDoubleClickResults,
  filePickerErrorCodes,
  filePickerLinkModes,
  TEMPORARY_LINK_TTL
} from './FilePicker/constants'
import Picker from './Picker'

const mockQuery = jest.fn()
const mockGetStackClient = jest.fn()
const mockGetDownloadLinkById = jest.fn()
const mockFindLinksByDoctype = jest.fn()
const mockCollection = jest.fn()
const mockCozyClient = jest.fn()
const mockBuildFileOrFolderByIdQuery = jest.fn(fileId => ({
  definition: () => ({ id: fileId }),
  options: { as: `io.cozy.files/${fileId}` }
}))
const mockBuildSharedDriveFileOrFolderByIdQuery = jest.fn(
  ({ fileId, driveId }) => ({
    definition: () => ({ id: fileId, driveId }),
    options: { as: `io.cozy.files/${driveId}/${fileId}` }
  })
)

jest.mock('@/lib/logger', () => ({
  __esModule: true,
  default: {
    warn: jest.fn()
  }
}))

jest.mock('@/queries', () => ({
  buildFileOrFolderByIdQuery: fileId => mockBuildFileOrFolderByIdQuery(fileId),
  buildSharedDriveFileOrFolderByIdQuery: params =>
    mockBuildSharedDriveFileOrFolderByIdQuery(params)
}))

jest.mock('cozy-client', () => {
  const generateWebLink = jest.fn()
  return {
    __esModule: true,
    default: function CozyClient(...args) {
      return mockCozyClient(...args)
    },
    Q: () => ({ getById: id => ({ id }) }),
    fetchPolicies: {
      olderThan: () => () => true
    },
    generateWebLink,
    models: {
      file: {
        isFile: item => item?.type === 'file'
      }
    },
    useClient: () => ({
      query: mockQuery,
      getStackClient: mockGetStackClient,
      collection: mockCollection,
      capabilities: {}
    })
  }
})

jest.mock('cozy-client/dist/models/sharing', () => ({
  makeSharingLink: jest.fn()
}))

let mockFilePickerProps

jest.mock('./FilePicker', () => props => {
  mockFilePickerProps = props
  return null
})

const mockFile = {
  _id: 'file-id',
  type: 'file',
  name: 'invoice.pdf',
  size: '42',
  mime: 'application/pdf'
}

const mockSecondFile = {
  _id: 'second-file-id',
  type: 'file',
  name: 'receipt.pdf',
  size: '84',
  mime: 'application/pdf'
}

const mockThirdFile = {
  _id: 'third-file-id',
  type: 'file',
  name: 'report.pdf',
  size: '126',
  mime: 'application/pdf'
}

const callOnChange = (...args) => mockFilePickerProps.onChange(...args)
const callOnFileDoubleClick = linkMode =>
  mockFilePickerProps.onFileDoubleClick(mockFile, linkMode)

const setup = ({ intent = null } = {}) => {
  const service = {
    terminate: jest.fn(),
    throw: jest.fn()
  }

  render(<Picker service={service} intent={intent} />)

  return { service }
}

describe('Picker', () => {
  beforeEach(() => {
    mockGetStackClient.mockReturnValue({ uri: 'https://alice.example' })
    mockFindLinksByDoctype.mockResolvedValue({ data: [] })
    mockCollection.mockReturnValue({
      findLinksByDoctype: mockFindLinksByDoctype,
      getDownloadLinkById: mockGetDownloadLinkById
    })
    mockCozyClient.mockReturnValue({
      collection: () => ({ getDownloadLinkById: mockGetDownloadLinkById })
    })
  })

  afterEach(() => {
    jest.clearAllMocks()
  })

  it('should pass the default filePickerConfig when the intent carries no data', () => {
    setup({ intent: null })

    expect(mockFilePickerProps.filePickerConfig.sharingLink).toEqual({
      allowFolder: true
    })
    expect(mockFilePickerProps.filePickerConfig.downloadLink).toEqual({
      allowFolder: false
    })
  })

  it('should pass the client-provided config from the intent to the FilePicker', () => {
    const intent = {
      attributes: {
        data: {
          sharingLink: { label: 'As link' },
          downloadLink: { label: 'As attachment' }
        }
      }
    }
    setup({ intent })

    expect(mockFilePickerProps.filePickerConfig.sharingLink).toEqual({
      allowFolder: true,
      label: 'As link'
    })
    expect(mockFilePickerProps.filePickerConfig.downloadLink).toEqual({
      allowFolder: false,
      label: 'As attachment'
    })
  })

  it('should render the FilePicker in multiple selection mode by default', () => {
    setup()

    expect(mockFilePickerProps.multiple).toBe(true)
  })

  it('should render the FilePicker in single selection mode when configured', () => {
    const intent = {
      attributes: {
        data: { multiple: false }
      }
    }
    setup({ intent })

    expect(mockFilePickerProps.multiple).toBe(false)
  })

  it('should refresh files before terminating with links generated by the access modal', async () => {
    mockQuery.mockResolvedValue({
      data: {
        ...mockFile,
        name: 'updated-invoice.pdf',
        size: '84'
      }
    })
    const { service } = setup()

    await callOnChange([mockFile], filePickerLinkModes.PUBLIC_LINK, [
      {
        documentId: 'file-id',
        url: 'https://drive.example/public?sharecode=abc'
      }
    ])

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(mockBuildFileOrFolderByIdQuery).toHaveBeenCalledWith('file-id')
    expect(mockQuery).toHaveBeenCalledWith(
      { id: 'file-id' },
      expect.objectContaining({
        as: 'picker-confirm-file-id',
        fetchPolicy: expect.any(Function)
      })
    )
    expect(makeSharingLink).not.toHaveBeenCalled()
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'updated-invoice.pdf',
        size: 84,
        mimeType: 'application/pdf',
        sharingLink: 'https://drive.example/public?sharecode=abc',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should revalidate a shared-drive file with its drive id', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    makeSharingLink.mockResolvedValue(
      'https://drive.example/public?sharecode=abc'
    )
    const { service } = setup()

    await callOnChange(
      { _id: 'file-id', driveId: 'drive-id' },
      filePickerLinkModes.PUBLIC_LINK
    )

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(mockBuildSharedDriveFileOrFolderByIdQuery).toHaveBeenCalledWith({
      fileId: 'file-id',
      driveId: 'drive-id'
    })
    expect(mockQuery).toHaveBeenCalledWith(
      { id: 'file-id', driveId: 'drive-id' },
      expect.objectContaining({
        as: 'io.cozy.files/drive-id/file-id',
        fetchPolicy: expect.any(Function)
      })
    )
  })

  it('should terminate with a bare array containing a public link entry', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    makeSharingLink.mockResolvedValue(
      'https://drive.example/public?sharecode=abc'
    )
    const { service } = setup()

    await callOnChange(mockFile, filePickerLinkModes.PUBLIC_LINK)

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).toHaveBeenCalledWith(expect.any(Object), [
      'file-id'
    ])
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        sharingLink: 'https://drive.example/public?sharecode=abc',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should terminate with a bare array containing public link entries', async () => {
    mockQuery.mockImplementation(({ id }) => {
      return Promise.resolve({
        data: id === 'file-id' ? mockFile : mockSecondFile
      })
    })
    makeSharingLink
      .mockResolvedValueOnce('https://drive.example/public?sharecode=abc')
      .mockResolvedValueOnce('https://drive.example/public?sharecode=def')
    const { service } = setup()

    await callOnChange(
      [mockFile, mockSecondFile],
      filePickerLinkModes.PUBLIC_LINK
    )

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).toHaveBeenCalledWith(expect.any(Object), [
      'file-id'
    ])
    expect(makeSharingLink).toHaveBeenCalledWith(expect.any(Object), [
      'second-file-id'
    ])
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        sharingLink: 'https://drive.example/public?sharecode=abc',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      },
      {
        id: 'second-file-id',
        name: 'receipt.pdf',
        size: 84,
        mimeType: 'application/pdf',
        sharingLink: 'https://drive.example/public?sharecode=def',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should terminate with a bare array containing a temporary download link entry', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    makeSharingLink.mockResolvedValue(
      'https://drive.example/public?sharecode=abc'
    )
    mockGetDownloadLinkById.mockResolvedValue(
      'https://alice.example/files/downloads/123/invoice.pdf?Dl=1'
    )
    const { service } = setup()

    await callOnChange(mockFile, filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK)

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).toHaveBeenCalledWith(
      expect.any(Object),
      ['file-id'],
      {
        ttl: TEMPORARY_LINK_TTL
      }
    )
    expect(mockCozyClient).toHaveBeenCalledWith({
      uri: 'https://alice.example',
      token: 'abc',
      useCustomStore: true
    })
    expect(mockGetDownloadLinkById).toHaveBeenCalledWith(
      'file-id',
      'invoice.pdf'
    )
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        downloadLink:
          'https://alice.example/files/downloads/123/invoice.pdf?Dl=1',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should use the shared drive API for a temporary download link', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    mockGetDownloadLinkById.mockResolvedValue(
      'https://alice.example/sharings/drives/drive-id/downloads/123'
    )
    const { service } = setup()

    await callOnChange(
      { _id: 'file-id', driveId: 'drive-id' },
      filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK
    )

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).not.toHaveBeenCalled()
    expect(mockCozyClient).not.toHaveBeenCalled()
    expect(mockGetDownloadLinkById).toHaveBeenCalledWith(
      'file-id',
      'invoice.pdf'
    )
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        downloadLink:
          'https://alice.example/sharings/drives/drive-id/downloads/123',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should use the corresponding shared drive API for each drive group', async () => {
    mockQuery.mockImplementation(({ id }) => {
      const files = {
        'file-id': mockFile,
        'second-file-id': mockSecondFile,
        'third-file-id': mockThirdFile
      }
      return Promise.resolve({ data: files[id] })
    })
    makeSharingLink.mockResolvedValue(
      'https://drive.example/public?sharecode=abc'
    )
    mockGetDownloadLinkById.mockImplementation(fileId =>
      Promise.resolve(`https://alice.example/downloads/${fileId}`)
    )
    const { service } = setup()

    await callOnChange(
      [
        { _id: 'file-id', driveId: 'drive-a' },
        { _id: 'second-file-id' },
        { _id: 'third-file-id', driveId: 'drive-b' }
      ],
      filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK
    )

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(mockCollection).toHaveBeenNthCalledWith(1, 'io.cozy.files', {
      driveId: 'drive-a'
    })
    expect(mockCollection).toHaveBeenNthCalledWith(2, 'io.cozy.files', {
      driveId: 'drive-b'
    })
    expect(makeSharingLink).toHaveBeenCalledWith(
      expect.any(Object),
      ['second-file-id'],
      { ttl: TEMPORARY_LINK_TTL }
    )
    expect(service.terminate.mock.calls[0][0]).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: 'file-id',
          downloadLink: 'https://alice.example/downloads/file-id'
        }),
        expect.objectContaining({
          id: 'second-file-id',
          downloadLink: 'https://alice.example/downloads/second-file-id'
        }),
        expect.objectContaining({
          id: 'third-file-id',
          downloadLink: 'https://alice.example/downloads/third-file-id'
        })
      ])
    )
    expect(service.terminate.mock.calls[0][0].map(entry => entry.id)).toEqual([
      'file-id',
      'second-file-id',
      'third-file-id'
    ])
  })

  it('should use one temporary sharing link for multiple download links', async () => {
    mockQuery.mockImplementation(({ id }) => {
      return Promise.resolve({
        data: id === 'file-id' ? mockFile : mockSecondFile
      })
    })
    makeSharingLink.mockResolvedValue(
      'https://drive.example/public?sharecode=abc'
    )
    mockGetDownloadLinkById
      .mockResolvedValueOnce(
        'https://alice.example/files/downloads/123/invoice.pdf?Dl=1'
      )
      .mockResolvedValueOnce(
        'https://alice.example/files/downloads/456/receipt.pdf?Dl=1'
      )
    const { service } = setup()

    await callOnChange(
      [mockFile, mockSecondFile],
      filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK
    )

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).toHaveBeenCalledTimes(1)
    expect(makeSharingLink).toHaveBeenCalledWith(
      expect.any(Object),
      ['file-id', 'second-file-id'],
      {
        ttl: TEMPORARY_LINK_TTL
      }
    )
    expect(mockCozyClient).toHaveBeenCalledTimes(1)
    expect(mockGetDownloadLinkById).toHaveBeenNthCalledWith(
      1,
      'file-id',
      'invoice.pdf'
    )
    expect(mockGetDownloadLinkById).toHaveBeenNthCalledWith(
      2,
      'second-file-id',
      'receipt.pdf'
    )
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        downloadLink:
          'https://alice.example/files/downloads/123/invoice.pdf?Dl=1',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      },
      {
        id: 'second-file-id',
        name: 'receipt.pdf',
        size: 84,
        mimeType: 'application/pdf',
        downloadLink:
          'https://alice.example/files/downloads/456/receipt.pdf?Dl=1',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  describe('double-click action', () => {
    it('should create a temporary download link for the double-clicked file', async () => {
      mockQuery.mockResolvedValue({ data: mockFile })
      makeSharingLink.mockResolvedValue(
        'https://drive.example/public?sharecode=abc'
      )
      mockGetDownloadLinkById.mockResolvedValue(
        'https://alice.example/files/downloads/123/invoice.pdf?Dl=1'
      )
      const { service } = setup()

      await callOnFileDoubleClick(filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK)

      await waitFor(() => expect(service.terminate).toHaveBeenCalled())
      expect(mockBuildFileOrFolderByIdQuery).toHaveBeenCalledWith('file-id')
      expect(mockGetDownloadLinkById).toHaveBeenCalledWith(
        'file-id',
        'invoice.pdf'
      )
      expect(service.terminate).toHaveBeenCalledWith([
        {
          id: 'file-id',
          name: 'invoice.pdf',
          size: 42,
          mimeType: 'application/pdf',
          downloadLink:
            'https://alice.example/files/downloads/123/invoice.pdf?Dl=1',
          thumbnail: {
            link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
          }
        }
      ])
    })

    it('should revalidate and reuse an existing sharing link', async () => {
      mockQuery.mockResolvedValue({ data: mockFile })
      mockFindLinksByDoctype.mockResolvedValue({
        data: [
          {
            attributes: {
              permissions: { files: { values: ['file-id'] } },
              shortcodes: { code: 'existing-code' }
            }
          }
        ]
      })
      const { generateWebLink } = require('cozy-client')
      generateWebLink.mockReturnValue(
        'https://drive.example/public?sharecode=existing-code'
      )
      const { service } = setup()

      await callOnFileDoubleClick(filePickerLinkModes.PUBLIC_LINK)

      await waitFor(() => expect(service.terminate).toHaveBeenCalled())
      expect(mockFindLinksByDoctype).toHaveBeenCalledWith('io.cozy.files')
      expect(mockBuildFileOrFolderByIdQuery).toHaveBeenCalledWith('file-id')
      expect(makeSharingLink).not.toHaveBeenCalled()
      expect(service.terminate).toHaveBeenCalledWith([
        {
          id: 'file-id',
          name: 'invoice.pdf',
          size: 42,
          mimeType: 'application/pdf',
          sharingLink: 'https://drive.example/public?sharecode=existing-code',
          thumbnail: {
            link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
          }
        }
      ])
    })

    it('should open the modal when no sharing link exists', async () => {
      const { service } = setup()

      const result = await callOnFileDoubleClick(
        filePickerLinkModes.PUBLIC_LINK
      )

      expect(result).toBe(filePickerDoubleClickResults.OPEN_MODAL)
      expect(service.terminate).not.toHaveBeenCalled()
      expect(mockBuildFileOrFolderByIdQuery).not.toHaveBeenCalled()
    })

    it('should return a sharing error when an existing link has no sharecode', async () => {
      mockFindLinksByDoctype.mockResolvedValue({
        data: [
          {
            attributes: {
              permissions: { files: { values: ['file-id'] } }
            }
          }
        ]
      })
      const { service } = setup()

      const result = await callOnFileDoubleClick(
        filePickerLinkModes.PUBLIC_LINK
      )

      expect(result).toBe(filePickerErrorCodes.SHARING_LINK_FAILED)
      expect(service.terminate).not.toHaveBeenCalled()
      expect(mockBuildFileOrFolderByIdQuery).not.toHaveBeenCalled()
    })

    it('should return a sharing error when checking existing links fails', async () => {
      mockFindLinksByDoctype.mockRejectedValue(
        new Error('sharing lookup failed')
      )
      const { service } = setup()

      const result = await callOnFileDoubleClick(
        filePickerLinkModes.PUBLIC_LINK
      )

      expect(result).toBe(filePickerErrorCodes.SHARING_LINK_FAILED)
      expect(service.terminate).not.toHaveBeenCalled()
      expect(mockBuildFileOrFolderByIdQuery).not.toHaveBeenCalled()
    })
  })

  it('should return an ITEM_NOT_FOUND error code when metadata loading fails', async () => {
    mockQuery.mockRejectedValue(new Error('not found'))
    const { service } = setup()

    const result = await callOnChange(mockFile, filePickerLinkModes.PUBLIC_LINK)

    expect(result).toBe(filePickerErrorCodes.ITEM_NOT_FOUND)
    expect(service.throw).not.toHaveBeenCalled()
    expect(service.terminate).not.toHaveBeenCalled()
  })

  it('should reuse an existing sharing link instead of creating a new one', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    mockFindLinksByDoctype.mockResolvedValue({
      data: [
        {
          attributes: {
            permissions: {
              files: {
                values: ['file-id']
              }
            },
            shortcodes: {
              code: 'existing-code'
            }
          }
        }
      ]
    })
    const { generateWebLink } = require('cozy-client')
    generateWebLink.mockReturnValue(
      'https://drive.example/public?sharecode=existing-code'
    )
    const { service } = setup()

    await callOnChange(mockFile, filePickerLinkModes.PUBLIC_LINK)

    await waitFor(() => expect(service.terminate).toHaveBeenCalled())
    expect(makeSharingLink).not.toHaveBeenCalled()
    expect(service.terminate).toHaveBeenCalledWith([
      {
        id: 'file-id',
        name: 'invoice.pdf',
        size: 42,
        mimeType: 'application/pdf',
        sharingLink: 'https://drive.example/public?sharecode=existing-code',
        thumbnail: {
          link: 'https://files.twake.app/email-assets/file-picker/pdf.png'
        }
      }
    ])
  })

  it('should return a SHARING_LINK_FAILED error code when public link generation fails', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    makeSharingLink.mockRejectedValue(new Error('sharing failed'))
    const { service } = setup()

    const result = await callOnChange(mockFile, filePickerLinkModes.PUBLIC_LINK)

    expect(result).toBe(filePickerErrorCodes.SHARING_LINK_FAILED)
    expect(service.throw).not.toHaveBeenCalled()
    expect(service.terminate).not.toHaveBeenCalled()
  })

  it('should return a DOWNLOAD_LINK_FAILED error code when temporary link generation fails', async () => {
    mockQuery.mockResolvedValue({ data: mockFile })
    makeSharingLink.mockResolvedValue('https://drive.example/public')
    const { service } = setup()

    const result = await callOnChange(
      mockFile,
      filePickerLinkModes.TEMPORARY_DOWNLOAD_LINK
    )

    expect(result).toBe(filePickerErrorCodes.DOWNLOAD_LINK_FAILED)
    expect(service.throw).not.toHaveBeenCalled()
    expect(service.terminate).not.toHaveBeenCalled()
  })
})
