packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
  conflicts_@types/amqplib_0_10_7:
    '@types/amqplib': 0.10.7
  conflicts_conflicts_@types/amqplib_0_10_7_h0_10_7:
    '@types/amqplib': ^0.10.7
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
catalog:
  '@types/amqplib': ^0.10.7
  amqplib: ^0.10.7
  axios: ^1.8.4
  cozy-client: ^57.6.0
