name: docker-build

on:
  pull_request:
    branches: [main]
    paths:
      - "tdrive/docker/**"

jobs:
  build-frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: cd tdrive && docker build -t tdrive/tdrive-frontend -f docker/tdrive-frontend/Dockerfile .

  build-node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: cd tdrive && docker build --target production -t docker-registry.linagora.com/tdrive/tdrive-node -f docker/tdrive-node/Dockerfile .
